insert into drinks (drink_id, drink_name, price, img, description, category) values (1, 'latte', 3.00, 'latte', 'Rich and creamy latte with caramel', 'Espresso');
insert into drinks (drink_id, drink_name, price, img, description, category) values (2, 'cappuccino', 4.00, 'cappuccino', 'Like a latte, but with added foam', 'Espresso');
insert into drinks (drink_id, drink_name, price, img, description, category) values (3, 'espresso', 8.00, 'espresso', 'A shot of hard-edged, dark espresso', 'Espresso');
insert into drinks (drink_id, drink_name, price, img, description, category) values (4, 'macchiato', 5.00, 'macchiato', 'Espresso with a small dash of milk', 'Espresso');
insert into drinks (drink_id, drink_name, price, img, description, category) values (5, 'americano', 4.00, 'americano', 'Flavorful americano with almond milk', 'Americano');
insert into drinks (drink_id, drink_name, price, img, description, category) values (6, 'mocha', 5.00, 'mocha', 'Decadent mocha with cream and fudge', 'Espresso');
insert into drinks (drink_id, drink_name, price, img, description, category) values (7, 'flat white', 3.00, 'flat white', 'Foamy and frothy flat white w/ honey', 'Americano');
insert into drinks (drink_id, drink_name, price, img, description, category) values (8, 'affogato', 4.00, 'affogato', 'Espresso, liqueur, and vanilla ice cream', 'Cold Drink');
insert into drinks (drink_id, drink_name, price, img, description, category) values (9, 'cold brew', 6.00, 'cold brew', 'Refreshing cold brew with a lemon', 'Cold Drink');
insert into drinks (drink_id, drink_name, price, img, description, category) values (10, 'frappe', 3.00, 'frappe', 'Affogato with a scoop of ice cream', 'Cold Drink');